// Code generated by re2dfa (https://github.com/opennota/re2dfa).

package main

import "unicode/utf8"

func matchMSIE(s string) (end int) {
	end = -1
	var r rune
	var rlen int
	i := 0
	_, _, _ = r, rlen, i
	r, rlen = utf8.DecodeRuneInString(s[i:])
	if rlen == 0 {
		return
	}
	i += rlen
	switch {
	case r <= 9 || r >= 11 && r <= 76 || r >= 78:
		goto s2
	case r == 77:
		goto s3
	}
	return
s2:
	r, rlen = utf8.DecodeRuneInString(s[i:])
	if rlen == 0 {
		return
	}
	i += rlen
	switch {
	case r <= 9 || r >= 11 && r <= 76 || r >= 78:
		goto s2
	case r == 77:
		goto s3
	}
	return
s3:
	r, rlen = utf8.DecodeRuneInString(s[i:])
	if rlen == 0 {
		return
	}
	i += rlen
	switch {
	case r == 77:
		goto s3
	case r == 83:
		goto s4
	case r <= 9 || r >= 11 && r <= 76 || r >= 78 && r <= 82 || r >= 84:
		goto s2
	}
	return
s4:
	r, rlen = utf8.DecodeRuneInString(s[i:])
	if rlen == 0 {
		return
	}
	i += rlen
	switch {
	case r == 77:
		goto s3
	case r <= 9 || r >= 11 && r <= 72 || r >= 74 && r <= 76 || r >= 78:
		goto s2
	case r == 73:
		goto s5
	}
	return
s5:
	r, rlen = utf8.DecodeRuneInString(s[i:])
	if rlen == 0 {
		return
	}
	i += rlen
	switch {
	case r <= 9 || r >= 11 && r <= 68 || r >= 70 && r <= 76 || r >= 78:
		goto s2
	case r == 69:
		end = i
		goto s6
	case r == 77:
		goto s3
	}
	return
s6:
	r, rlen = utf8.DecodeRuneInString(s[i:])
	if rlen == 0 {
		return
	}
	i += rlen
	switch {
	case r <= 9 || r >= 11 && r <= 76 || r >= 78:
		end = i
		goto s7
	case r == 77:
		end = i
		goto s8
	}
	return
s7:
	r, rlen = utf8.DecodeRuneInString(s[i:])
	if rlen == 0 {
		return
	}
	i += rlen
	switch {
	case r == 77:
		end = i
		goto s8
	case r <= 9 || r >= 11 && r <= 76 || r >= 78:
		end = i
		goto s7
	}
	return
s8:
	r, rlen = utf8.DecodeRuneInString(s[i:])
	if rlen == 0 {
		return
	}
	i += rlen
	switch {
	case r == 83:
		end = i
		goto s9
	case r <= 9 || r >= 11 && r <= 76 || r >= 78 && r <= 82 || r >= 84:
		end = i
		goto s7
	case r == 77:
		end = i
		goto s8
	}
	return
s9:
	r, rlen = utf8.DecodeRuneInString(s[i:])
	if rlen == 0 {
		return
	}
	i += rlen
	switch {
	case r <= 9 || r >= 11 && r <= 72 || r >= 74 && r <= 76 || r >= 78:
		end = i
		goto s7
	case r == 10:
	case r == 73:
		end = i
		goto s11
	case r == 77:
		end = i
		goto s8
	}
	return
s11:
	r, rlen = utf8.DecodeRuneInString(s[i:])
	if rlen == 0 {
		return
	}
	i += rlen
	switch {
	case r == 77:
		end = i
		goto s8
	case r <= 9 || r >= 70 && r <= 76 || r >= 78:
		end = i
		goto s7
	case r == 69:
		end = i
		goto s12
	}
	return
s12:
	r, rlen = utf8.DecodeRuneInString(s[i:])
	if rlen == 0 {
		return
	}
	i += rlen
	switch {
	case r <= 9 || r >= 11 && r <= 76 || r >= 78:
		end = i
		goto s7
	case r == 77:
		end = i
		goto s8
	}
	return
}
