// Code generated by re2dfa (https://github.com/opennota/re2dfa).

package main

import "unicode/utf8"

func matchAndroid(s string) (end int) {
	end = -1
	var r rune
	var rlen int
	i := 0
	_, _, _ = r, rlen, i
	r, rlen = utf8.DecodeRuneInString(s[i:])
	if rlen == 0 {
		return
	}
	i += rlen
	switch {
	case r <= 9 || r >= 11 && r <= 64 || r >= 66:
		goto s2
	case r == 65:
		goto s3
	}
	return
s2:
	r, rlen = utf8.DecodeRuneInString(s[i:])
	if rlen == 0 {
		return
	}
	i += rlen
	switch {
	case r == 65:
		goto s3
	case r <= 9 || r >= 11 && r <= 64 || r >= 66:
		goto s2
	}
	return
s3:
	r, rlen = utf8.DecodeRuneInString(s[i:])
	if rlen == 0 {
		return
	}
	i += rlen
	switch {
	case r <= 9 || r >= 11 && r <= 64 || r >= 66 && r <= 109 || r >= 111:
		goto s2
	case r == 65:
		goto s3
	case r == 110:
		goto s4
	}
	return
s4:
	r, rlen = utf8.DecodeRuneInString(s[i:])
	if rlen == 0 {
		return
	}
	i += rlen
	switch {
	case r <= 9 || r >= 11 && r <= 64 || r >= 66 && r <= 99 || r >= 101:
		goto s2
	case r == 65:
		goto s3
	case r == 100:
		goto s5
	}
	return
s5:
	r, rlen = utf8.DecodeRuneInString(s[i:])
	if rlen == 0 {
		return
	}
	i += rlen
	switch {
	case r <= 9 || r >= 11 && r <= 64 || r >= 66 && r <= 113 || r >= 115:
		goto s2
	case r == 65:
		goto s3
	case r == 114:
		goto s6
	}
	return
s6:
	r, rlen = utf8.DecodeRuneInString(s[i:])
	if rlen == 0 {
		return
	}
	i += rlen
	switch {
	case r <= 9 || r >= 11 && r <= 64 || r >= 66 && r <= 110 || r >= 112:
		goto s2
	case r == 65:
		goto s3
	case r == 111:
		goto s7
	}
	return
s7:
	r, rlen = utf8.DecodeRuneInString(s[i:])
	if rlen == 0 {
		return
	}
	i += rlen
	switch {
	case r <= 9 || r >= 11 && r <= 64 || r >= 66 && r <= 104 || r >= 106:
		goto s2
	case r == 65:
		goto s3
	case r == 105:
		goto s8
	}
	return
s8:
	r, rlen = utf8.DecodeRuneInString(s[i:])
	if rlen == 0 {
		return
	}
	i += rlen
	switch {
	case r == 65:
		goto s3
	case r == 100:
		end = i
		goto s9
	case r <= 9 || r >= 11 && r <= 64 || r >= 66 && r <= 99 || r >= 101:
		goto s2
	}
	return
s9:
	r, rlen = utf8.DecodeRuneInString(s[i:])
	if rlen == 0 {
		return
	}
	i += rlen
	switch {
	case r <= 9 || r >= 11 && r <= 64 || r >= 66:
		end = i
		goto s10
	case r == 65:
		end = i
		goto s11
	}
	return
s10:
	r, rlen = utf8.DecodeRuneInString(s[i:])
	if rlen == 0 {
		return
	}
	i += rlen
	switch {
	case r <= 9 || r >= 11 && r <= 64 || r >= 66:
		end = i
		goto s10
	case r == 65:
		end = i
		goto s11
	}
	return
s11:
	r, rlen = utf8.DecodeRuneInString(s[i:])
	if rlen == 0 {
		return
	}
	i += rlen
	switch {
	case r == 65:
		end = i
		goto s11
	case r == 110:
		end = i
		goto s12
	case r <= 9 || r >= 11 && r <= 64 || r >= 66 && r <= 109 || r >= 111:
		end = i
		goto s10
	}
	return
s12:
	r, rlen = utf8.DecodeRuneInString(s[i:])
	if rlen == 0 {
		return
	}
	i += rlen
	switch {
	case r <= 9 || r >= 11 && r <= 64 || r >= 66 && r <= 99 || r >= 101:
		end = i
		goto s10
	case r == 65:
		end = i
		goto s11
	case r == 100:
		end = i
		goto s13
	}
	return
s13:
	r, rlen = utf8.DecodeRuneInString(s[i:])
	if rlen == 0 {
		return
	}
	i += rlen
	switch {
	case r <= 9 || r >= 11 && r <= 64 || r >= 66 && r <= 113 || r >= 115:
		end = i
		goto s10
	case r == 10:
	case r == 65:
		end = i
		goto s11
	case r == 114:
		end = i
		goto s15
	}
	return
s15:
	r, rlen = utf8.DecodeRuneInString(s[i:])
	if rlen == 0 {
		return
	}
	i += rlen
	switch {
	case r == 65:
		end = i
		goto s11
	case r == 111:
		end = i
		goto s16
	case r <= 9 || r >= 11 && r <= 64 || r >= 66 && r <= 110 || r >= 112:
		end = i
		goto s10
	case r == 10:
	}
	return
s16:
	r, rlen = utf8.DecodeRuneInString(s[i:])
	if rlen == 0 {
		return
	}
	i += rlen
	switch {
	case r <= 9 || r >= 11 && r <= 64 || r >= 66 && r <= 104 || r >= 106:
		end = i
		goto s10
	case r == 65:
		end = i
		goto s11
	case r == 105:
		end = i
		goto s17
	}
	return
s17:
	r, rlen = utf8.DecodeRuneInString(s[i:])
	if rlen == 0 {
		return
	}
	i += rlen
	switch {
	case r == 100:
		end = i
		goto s18
	case r <= 9 || r >= 66 && r <= 99 || r >= 101:
		end = i
		goto s10
	case r == 65:
		end = i
		goto s11
	}
	return
s18:
	r, rlen = utf8.DecodeRuneInString(s[i:])
	if rlen == 0 {
		return
	}
	i += rlen
	switch {
	case r <= 9 || r >= 11 && r <= 64 || r >= 66:
		end = i
		goto s10
	case r == 65:
		end = i
		goto s11
	}
	return
}
